[package]
name = "chifriends"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
dialoguer = "0.11.0"
rusqlite = "0.29.0"
serde = { version = "1.0.160" , features = ["derive"] }
serde_json = "1.0.96"
watchexec = "2.3.0"
